<?php 


/**
*  implementation of hook_form_alter
*/

function hs_basic_form_alter(&$form, &$form_state, $form_id) {
  switch($form_id) {
    case "commerce_checkout_form_checkout":
    $form['customer_profile_shipping']['commerce_customer_address']['#access'] = FALSE;
    global $user;
    $form['customer_profile_shipping']['#title'] = t('Информация о доставке');
    if ($user->uid != 0) {
      $profile = user_load($user->uid);    
  	  $form['customer_profile_shipping']['#title'] = t('Информация о доставке');
  	  $form['cart_contents']['cart_contents_view']['#markup'] = preg_replace('/<td class="component-title">Order total<\/td>/i', '<td class="component-title">Общая сумма заказа</td>', $form['cart_contents']['cart_contents_view']['#markup']);
  	  
      $form['customer_profile_shipping']['field_full_name']['und'][0]['value']['#default_value'] = $profile->field_full_name['und'][0]['value'];
      $form['customer_profile_shipping']['field_address']['und'][0]['value']['#default_value'] = $profile->field_address['und'][0]['value'];
      $form['customer_profile_shipping']['field_city']['und'][0]['value']['#default_value'] = $profile->field_city['und'][0]['value'];
      $form['customer_profile_shipping']['field_telephone']['und'][0]['value']['#default_value'] = $profile->field_telephone['und'][0]['value'];
    }
    break;
	case "commerce_checkout_form_review":
	  $form['checkout_review']['review']['#data']['customer_profile_shipping']['title'] = t('Информация о доставке');
      $form['checkout_review']['review']['#data']['cart_contents']['data'] = preg_replace('/<td class="component-title">Order total<\/td>/i', '<td class="component-title">Общая сумма заказа</td>', $form['checkout_review']['review']['#data']['cart_contents']['data']);
	  break;	
  case "comment_node_news_form":
    $form['comment_body']['und'][0]['#title'] = 'Комментарий';
    $form['subject']['#access'] = FALSE;
    break; 
  }
}

/**
 * implementation of hook_init
 */

function hs_basic_init() {
  global $user;
  if (!($user->uid == 1)) {
    if (arg(0) == 'node' && is_numeric(arg(1)) && arg(2) == 'products') {
      drupal_goto('node/' . arg(1));
    }
  }
}

/**
 * implementation of hook_menu_alter
 */

function hs_basic_menu_alter(&$items) {
  //dsm($items);
  $items['node/%node/products']['access callback'] = FALSE;
  
  $items['user/%user']['access callback'] = 'hs_basic_profile_view_access';
}

function hs_basic_profile_view_access($account) {
  global $user;
  if ($user->uid == 1) {
    return TRUE;
  }
  if ($user->uid == $account->uid) {
    return TRUE;
  }
  
  return FALSE;
}
